title: Presentation
baseurl: "/presentations"
defaults:
  -
    scope:
      path: ""
    values:
      layout: reveal

reveal:
  path: "/reveal.js"
  theme: black
  plugins:
    - highlight
  settings:
    controls: false
    progress: true
    history: true
    center: true
    transition: slide
